server:
  port: 3000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # 使用ip注册到eureka服务列表
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/ # 注册中心的注册地址
spring:
  application:
    name: plat-service
