server:
  port: 3000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
spring:
  application:
    name: plat-service
